{
  "description": "MONGODB-OIDC authentication with retry enabled",
  "schemaVersion": "1.18",
  "runOnRequirements": [
    {
      "minServerVersion": "7.0",
      "auth": true,
      "authMechanism": "MONGODB-OIDC"
    }
  ],
  "createEntities": [
    {
      "client": {
        "id": "failPointClient",
        "useMultipleMongoses": false
      }
    },
    {
      "client": {
        "id": "client0",
        "uriOptions": {
          "authMechanism": "MONGODB-OIDC",
          "authMechanismProperties": {
            "$$placeholder": 1
          },
          "retryReads": true,
          "retryWrites": true
        },
        "observeEvents": [
          "commandStartedEvent",
          "commandSucceededEvent",
          "commandFailedEvent"
        ]
      }
    },
    {
      "database": {
        "id": "database0",
        "client": "client0",
        "databaseName": "test"
      }
    },
    {
      "collection": {
        "id": "collection0",
        "database": "database0",
        "collectionName": "collName"
      }
    }
  ],
  "initialData": [
    {
      "collectionName": "collName",
      "databaseName": "test",
      "documents": [

      ]
    }
  ],
  "tests": [
    {
      "description": "Read commands should fail if reauthentication fails",
      "operations": [
        {
          "name": "find",
          "object": "collection0",
          "arguments": {
            "filter": {
            }
          },
          "expectResult": [

          ]
        },
        {
          "name": "failPoint",
          "object": "testRunner",
          "arguments": {
            "client": "failPointClient",
            "failPoint": {
              "configureFailPoint": "failCommand",
              "mode": {
                "times": 2
              },
              "data": {
                "failCommands": [
                  "find",
                  "saslStart"
                ],
                "errorCode": 391
              }
            }
          }
        },
        {
          "name": "find",
          "object": "collection0",
          "arguments": {
            "filter": {
            }
          },
          "expectError": {
            "errorCode": 391
          }
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "find": "collName",
                  "filter": {
                  }
                }
              }
            },
            {
              "commandSucceededEvent": {
                "commandName": "find"
              }
            },
            {
              "commandStartedEvent": {
                "command": {
                  "find": "collName",
                  "filter": {
                  }
                }
              }
            },
            {
              "commandFailedEvent": {
                "commandName": "find"
              }
            }
          ]
        }
      ]
    },
    {
      "description": "Write commands should fail if reauthentication fails",
      "operations": [
        {
          "name": "insertOne",
          "object": "collection0",
          "arguments": {
            "document": {
              "_id": 1,
              "x": 1
            }
          }
        },
        {
          "name": "failPoint",
          "object": "testRunner",
          "arguments": {
            "client": "failPointClient",
            "failPoint": {
              "configureFailPoint": "failCommand",
              "mode": {
                "times": 2
              },
              "data": {
                "failCommands": [
                  "insert",
                  "saslStart"
                ],
                "errorCode": 391
              }
            }
          }
        },
        {
          "name": "insertOne",
          "object": "collection0",
          "arguments": {
            "document": {
              "_id": 2,
              "x": 2
            }
          },
          "expectError": {
            "errorCode": 391
          }
        }
      ],
      "expectEvents": [
        {
          "client": "client0",
          "events": [
            {
              "commandStartedEvent": {
                "command": {
                  "insert": "collName",
                  "documents": [
                    {
                      "_id": 1,
                      "x": 1
                    }
                  ]
                }
              }
            },
            {
              "commandSucceededEvent": {
                "commandName": "insert"
              }
            },
            {
              "commandStartedEvent": {
                "command": {
                  "insert": "collName",
                  "documents": [
                    {
                      "_id": 2,
                      "x": 2
                    }
                  ]
                }
              }
            }
          ]
        }
      ]
    }
  ]
}
